### ISSUE TITLE
[Forvaltningsportalen] Justere rekkefølge på valgte kartlag og endre multiply

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart#1459]
Denne issuen ser ut til å være ganske omfattende.

### Lik rendering av ting -> Merget i master
- [x] refaktorere en del internt i Kartlag Leaflet funksjonene for å kunne justere ting uten at det påvirker i loop. Denne var meget stor. Fjernet mange unødvendige mellomledd som tidligere har vært tiltenkt ikke lenger relevant funksjon.

### Blend Mode -> Merget i master
- [x] Legge til mulighet for å endre blend mode per lag fra kartlag fanen (knapp etc)
- [x] Rydde litt i visningen i kartlagfanen så det ikke tar opp så enormt med plass å justere på underelementene
- [X] Håndter problemstillinger med blend type endringer
- [X] Legg til støtte for kartlagstegneren IndexedRaster
- [x] Legg til blend mode støtte i gradientlag
- [x] Legg til en egen slider for global Alpha for et lag sin translucent variant.

### Next up
- [ ] Legg til støtte for global alpha for multiply også? eller unødvendig?
- [ ] skjul menyer der de ikke kan brukes, og dropp å endre i vector og art inntil det er fler av typene. Art skal uansett totalt revurderes på et senere tidspunkt.
- [ ] Beautify, slideren på gradient opacity helfarge ser funky ut

### Order
- [ ] Legge til mulighet for å ta tak i og endre rekkefølge på AKTIVE kartlag (starter her) internt i state'en hvor de huskes
- [ ] Endre rekkefølgen de tegnes ut i kartlaglisten
- [ ] Endre rekkefølgen de rendres i karttegneren
- [ ] Legg til en drag'n drop versjon eller noe slikt. Bruk piltaster for tab versjon?

**Comment by runningbones** [comment]
Endring av tegnerekkefølge på "tema", ikke hvert enkelt lag
