### ISSUE TITLE
Vis artsdata

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart#1464]
- Hent inn all artsinfo, ikke bare relevant for nin-info.
- Lever eget faktaark

**Comment by helemork** [comment]
@bjornreppen Dette er den issuen jeg regner med du prioriterer for tiden.
Jeg ser ennå ikke artsinfo på f.eks brunbjørn, så regner med GBIF lastejobben er på vei og at det blir knallbra. Det jeg lurer på er om vi automatisk får generert opp overelementene i nodene (typ bjørn som består av kun brunbjørn ) eller frosker som har omtrent 3-4 arter, eller om dette må gjøres uavhengig? Det er jo mulig noen har rapportert ting kun som frosk og bjørn, og så har man i tillegg de nedenfor, og da vil vi jo vise begge deler egentlig.

**Comment by bjornreppen** [comment]
Ja, alle aggregeres opp hele veien til Biota som da vil ha alle observasjoner av liv i seg.
