### ISSUE TITLE
LA-RE: slå sammen alle relieffgradienter til et heldekkende kontinuerlig datasett

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart#1471]

**Comment by bjornreppen** [comment]
Alternativt kanskje vi kan komme ut med et sett gradienter som igjen bygger et sett gradienter som definerer typene?   For eksempel tererengposisjon?

**Comment by helemork** [comment]
Vi kan ikke endre dette, det er opp til NiN-klassifikasjonen. Selv om det hadde vært behagelig i appen...
