### ISSUE TITLE
Jobb med leverandører for å få dem til å sette opp sine web servere med CORS

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart#1493]
Relatert til https://github.com/Artsdatabanken/nin-kart-frontend/issues/1483

Tjenester som må omkonfigureres (fra den initielle lista): 

 - [ ]  https://kart.miljodirektoratet.no/arcgis/services/vern/mapserver/WMSServer?service=wms&request=getcapabilities
 - [ ]  https://kart.miljodirektoratet.no/arcgis/services/naturtyper_nin/MapServer/WMSServer?service=wms&version=1.1.1&request=getcapabilities
 - [ ]  https://kart.miljodirektoratet.no/arcgis/services/naturtyper_hb13/mapserver/WMSServer?request=GetCapabilities&service=WMS
 - [ ]  https://kart.miljodirektoratet.no/arcgis/services/naturtyper_marine_hb19/MapServer/WMSServer?service=wms&version=1.1.1&request=getcapabilities
 - [ ]  https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte/mapserver/WMSServer?service=wms&request=getcapabilities
 - [ ]  https://kart.miljodirektoratet.no/arcgis/services/artnasjonal/mapserver/WMSServer?service=wms&version=1.1.1&request=getcapabilities

**Comment by bjornreppen** [comment]
Web serveren må returnere en headerlinje i HTTP responsen som inneholder
```
Access-Control-Allow-Origin: *
```

for å teste kan man inspisere network i browserens developer console eller f.eks. gjøre 
```
curl -v url
```

**Comment by bjornreppen** [comment]
Signaler fra leverandør om at dette er teknisk vanskelig i ESRI.  Ny strategi: Laste ned datasettene fra GeoNorge og serve dem lokalt.

**Comment by helemork** [comment]
Jeg tror kanskje ikke vi skal lukke denne. Arild ønsker å ta et møte med alle for å bli enige før vi bestemmer noe, oss på it og de på bio, sjefer inkludert. Kan du booke det inn, @runningbones ?
