### ISSUE TITLE
Landemerker, bruk bedre markup-element.

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart#1503]
Her er det vel react som ikke kompilerer ting til de elementene den burde automatisk, så vi kan dumpe det inn i steden.

### Use landmarks to describe the different areas of the pages
Landmarks are quite new in HTML but offer a possibility to indicate the purpose of different areas. There are several landmarks, and we recommend using them to make it easier to understand the interface for users who cannot see it.

### Suggested solution
Priority of landmarks:
1.	<nav> Use this element for navigation (i.e. the menu button/and menu that pops up, and the left navigation area on the information pages). You can have more than one <nav> element.
2.	<main> Use this element for the main article/main content area. Only use one <main> element.
3.	<header> and <footer> are used for the page header and footer.
There are more landmarks and a good practice, but not a requirement, is to make sure all content of the page is placed in landmarks.
### Priority (1-4)
Medium (3) 
### WCAG relation
1.3.1 Info and relationships (level A)
4.1.2 Name, Role, Value (level A)

**Comment by bjornreppen** [comment]
React?  Du mener kanskje material-ui? :-)

**Comment by helemork** [comment]
### Make sure that the HTML code follow the HTML standard 
[H: virkelig, skal vi validere koden og, det hadde vi _aldri_ tenkt på] 

WCAG lists 4 types of errors that is not acceptable in the HTML code. Several pages do have errors in the HTML code, and we recommend not only correcting the errors that are listed in WCAG but all issues that you are able to correct.

### Suggested solution
1.	Use W3C Markup Validation Service (https://validator.w3.org/) to validate the code. Make sure to validate the code as it is after script is executed. You can do this by… 
2.	View the code in the browser by pressing F12 after the page has loaded.
3.	Right click at the HTML element and select “Copy Outer HTML”. 
4.	In the validation service you need to write the correct doctype by hand, then you can paste the HTML code.

### Priority (1-4)
Low (4) 
### WCAG relation
4.1.1 Parsing (level A)

**Comment by helemork** [comment]
Denne blir mer eller mindre ok i neste versjon.
Lukker den da det ikke er en konkret issue.
