### ISSUE TITLE
Fargeprofil. 

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart#1504]
Nå bruker vi fager vi hentet ut fra NiN-siden, men det er et par forhold som ikke har høy nok kontrast. 

### Ting vi kunne tenkt oss der for å gjøre det lettere for oss selv:
- [x] Legge inn støtte for css-variabler
- [x] Bruke disse så det er lett å swappe mellom profilfarger etterhvert
- [x] Midlertidig bytte ut for å oppnå riktig kontrastforhold i de fleste situasjoner.
- [ ] Utarbeide en fargeprofil som faktisk er brukandes osv.

### Samarbeid mellom team
* @tovelitovela og grafiker bør i det minste involveres, men jeg antar det er andre nin-folk som sikkert har en sterk mening om hvordan ting bør se ut.

### Hvorfor er ting som de er?
Denne burde jo være relatert til prosjektets profil som helhet, og innfri alle krav til farger.
* Vi kan ikke benytte de orange fargene til adb om vi skal holde oss innenfor lovpålagte fargekrav, og gikk derfor for den grafiske fargesammensetningen som ligger på https://www.artsdatabanken.no/NiN/Systemet og https://www.artsdatabanken.no/nin/landskap 
* Disse manglet også et øvre mørkt nivå som vi har lagt til.
* @runningbones nevnte at enkelte samarbeidspartnere ønsket at denne siden ikke skal være ekstremt adb-brandet (om jeg husker riktig), og da landet vi på en mer nøytral variant. Det positive med grønnblå tone er at de ikke er naturlige varselfarger slik som orange.
* Henger sammen med https://github.com/Artsdatabanken/grafiskprofil
* Jo fortere vi får på plass total grafisk profil for adb/nin/nin-kart, jo mindre dobbeltarbeid blir det å endre på illustrasjonene vi lager...
* Se punktet nedenfor.

**Comment by helemork** [comment]
Fra rapporten:
### 
Some colour contrast problems in the content
Using good contrasts between text and the background is important to users with visual impairments. WCAG do have some requirements here. On a scale from 1:1 (no contrast) to 21:1 (black-white) ordinary text need a contrast ratio of at least 4.5:1. Large text (main headings) and graphics require a contrast of at least 3:1.

### Om the start page contrasts are quite low.
 
![bilde](https://user-images.githubusercontent.com/17450081/65226321-f0cf2d80-dac6-11e9-8f1f-0f51e1a1ae68.png)

The blue/green colour used as background colour to the white text, have a contrast ratio of 2.3:1 with the white text, which is clearly below the requirements both for ordinary text and large text. The slightly darker blue/green colour used for headings both on this page and pages in the rest of the interface have a contrast ratio of 3.6:1 which is acceptable for large headings but not for ordinary text. Since the text used in headings is quite thin, we would recommend using a darker colour even if the colour formally meets the requirements in large headings. Thin text contributes to making the text harder to read.
The grey icons and text at the bottom of the page have a contrast ratio of 4.478:1 which is just below the threshold. When highlighted (mouse over) the grey colour is darker, but the blue/green background makes the contrast ratio to fall to 3.8:1 which is too low. The text needs a contrast ratio of at least 4.5:1.

### Priority (1-4)
Medium (3)

### WCAG relation

1.4.3 Contrast (Minimum) (level AA)
1.4.11 Non-text contrast (level AA)

**Comment by helemork** [comment]
Dette er forøvrig et slikt punkt det hadde vært fint å ta en diskusjon på sammen med grafiker + tove.

**Comment by bjornreppen** [comment]
Kjempebra... og... de burde jo være her også det skjer... og kommentere rett på issues? ;-)

**Comment by helemork** [comment]
Har midlertidig dumpet inn én mørkere farge, mend ette er jo ikke en pallett. Så funks, men resten er gjeldende. Og ja, de har blitt invitert, men det var ikke øverst på todo-listen.

**Comment by helemork** [comment]
Fikses i NiN-kart 2.0
