### ISSUE TITLE
Lesbare artsnavn

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart#1535]
Bra jobba med vitenskapelige navn, forslag til oppgradering: 

- [x] Sette vitenskapelig navn på ny linje, evt. i parentes (istedet for italics) så brukere enklere forstår at det er 2 separate ting
- [x] Ikke vis vitenskapelig navn to ganger for arter som ikke har "lokalt navn, eksempel http://localhost:3000/Biota/Animalia/Acanthocephala/Archiacanthocephala
- [x] Vis taksonomisk nivå (Rike, rekke...) - ligger i metadata.json under nøkkel "nivå".

Artfakta.se: 
![image](https://user-images.githubusercontent.com/281359/65574334-7fcbc200-df6d-11e9-9414-e0749af83056.png)
https://artfakta.se/artbestamning/taxon/224202

Wikipedia:
![image](https://user-images.githubusercontent.com/281359/65574367-97a34600-df6d-11e9-96bc-fb011852bd0c.png)
https://en.wikipedia.org/wiki/Pallas%27s_squirrel

EOL: 
![image](https://user-images.githubusercontent.com/281359/65548547-f2ac4d00-df1b-11e9-89b3-ac713c522862.png)

**Comment by helemork** [comment]
Her tenker jeg kanskje noen av biologene, f.eks. @tovelitovela har innspill på hvordan vi best bør gjøre det så det samsvarer sånn mer eller mindre med hovedsiden. Så @svetlnaumova, hva om du tar en prat med dem først?

**Comment by helemork** [comment]
@bjornreppen har vi resten av infoen her fra navnebasen (navn på bestemmer og årstall? For det er nødvendig for å sikre at folk forstår hvilken art når det er arter med like latinske navn osv)

**Comment by bjornreppen** [comment]
Autor og årstall ligger under noden autor, eks: 
![image](https://user-images.githubusercontent.com/281359/65666662-6b0b2f00-e03e-11e9-9268-f5a248ad6f97.png)
https://data.artsdatabanken.no/Biota/Protozoa/Rhizaria/Radiolaria/metadata.json

**Comment by bjornreppen** [comment]
Taksonomisk nivå ligger tilgjengelig under nøkkelsen "nivå", eks:
![image](https://user-images.githubusercontent.com/281359/65667011-2207aa80-e03f-11e9-9c33-64deeb611ee1.png)
https://data.artsdatabanken.no/Biota/Protozoa/Rhizaria/Radiolaria/metadata.json

**Comment by bjornreppen** [comment]
Relatert til #1540

**Comment by tovelitovela** [comment]
@bjornreppen @helemork @svetlnaumova 
Det korrekte vil være å skrive: enellerannengulblomst _Galium verum_ subsp. _verum_ L.
Populærnavnet kan skrives med stor bokstav i overskrifter fordi overskrift, men i utgangspunktet er det kun latinsk navn som har stor bokstav. Authorstrengen hører til vitenskapelig navn og er i en del tilfeller nødvendig for å skille to navn fra hverandre, men om dere egentlig trenger å vise den til deres bruk her er ikke sikkert. Vi ønsker å vise den mye mindre enn vi gjør i dag på taksonsider og Arter på nett. Den er noen ganger lang og støyende.

Vitenskapelig navn kan ikke stå i parentes i stedet for italics, fordi italics er en greie i artsnavneverden. Her må vi jo vise at vi er mer seriøse nerder enn Wikipedia! ;D

**Comment by svetlnaumova** [comment]
@tovelitovela er det overkill hvis det ser sånn ut? Og skal vitenskapelige navn i navigasjonsmenyen (til venstre) også være i italics?

![Taxonomy](https://user-images.githubusercontent.com/43623201/66129727-c619c480-e5f0-11e9-8ee7-935b36fb806f.jpg)

**Comment by svetlnaumova** [comment]
Og hvis det finnes både populært navn og vitenskapelig navn, så vises først populærnavn og så vitenskapelig navn på linjen under.

![Taxonomy_2](https://user-images.githubusercontent.com/43623201/66129888-1002aa80-e5f1-11e9-94a8-f9dc20ecbadd.jpg)

**Comment by tovelitovela** [comment]
@svetlnaumova 
Jeg glemte helt å nevne at kursivering av latinsk navn bare skal gjøres på slektsnavn og nivåer under. Altså slekter, arter, underarter/varieteter:

**Rike** Dyreriket Animalia
 **Rekke** Ryggstrengdyr Chordata
  **Underrekke** Virveldyr Vertebrata
   **Klasse** Strålefinnefisker Actinopterygii
    **Orden** Torskefisker Gadiformes
     **Familie** Torskefamilien Gadidae
      **Slekt** _Gadus_ Linnaeus, 1758
       **Art** Torsk _Gadus morhua_ Linnaeus, 1758

Navn som skal kursiveres må gjerne være kursivert i menyen også. Det er slik vi har gjort det på nettsiden.

Det ser veldig bra ut med populærnavn øverst og vitenskapelig på linjen under!
