### ISSUE TITLE
Manglende Artsdatabanken-logo i hamburger-meny

### ISSUE THREAD

**Issue by svetlnaumova** [Artsdatabanken/nin-kart#1550]
Logoen til Artsdatabanken vises ikke i den nederste delen av hamburger-menyen. 

Burde også legge til "External link"-symbol (dette fikser jeg).

![06 (2)](https://user-images.githubusercontent.com/43623201/65774389-6f1e7600-e13e-11e9-8ac1-29056fa483d6.jpg)

**Comment by bjornreppen** [comment]
Kan det være at du testa mens @Myrdrahl  holdt på med noe vedlikehold?  Det ser ut som logoen kommer opp nå, men den er fortsatt litt merkelig plassert:

![image](https://user-images.githubusercontent.com/281359/65798204-4fed0c00-e171-11e9-83ff-49076e41a771.png)
