### ISSUE TITLE
Versjonsnummerering av API-tjenester

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart#1561]
**Is your feature request related to a problem? Please describe.**
Etabler system for versjonering av API

**Comment by bjornreppen** [comment]
Er enig, men tviler på at vi har kapasitet til å håndtere dette uten økt bemanning.

**Comment by bjornreppen** [comment]
APIer nå med versjonsnummer i start av path, eksempel https://punkt.artsdatabanken.no/v1/punkt?lat=63&lng=10.5
