### ISSUE TITLE
Hvordan gjør man drag'n'drop endring av kartlagrekkefølge lett å bruke for en med tastatrløsning

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart#1562]

**Comment by bjornreppen** [comment]
The W3.org site gives an accessible drag-and-drop example that offers the following key controls:
- Use the Tab to move to the item you want to move.
- Select the item you want to move with the Spacebar.
- Use the Up and Down cursor keys to select a target in the context menu.
- Press Enter to move the item to the target list.

https://dev.opera.com/articles/accessible-drag-and-drop/example.html

**Comment by helemork** [comment]
Dette støtter vi ikke. Og det er heller ikke realistisk å støtte det i noen umiddelbar fremtid.
