### ISSUE TITLE
Bakgrunnskart: sjøkart

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart#1573]
Ønske om også sjøkart i tillegg til de som ligger der:

https://kartkatalog.geonorge.no/metadata/917a592f-9a7c-48a8-91e5-63f12287f102

**Comment by bjornreppen** [comment]
Done:
- kyst
- havn
- svalbard
- omriss

![image](https://user-images.githubusercontent.com/281359/66112616-7d9be000-e5cb-11e9-95f5-0c85fc56d586.png)
