### ISSUE TITLE
Navigering: Kode wrappes over i ny linje

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart#1577]
Se NINA her:
![image](https://user-images.githubusercontent.com/281359/66324035-0c3e9300-e925-11e9-9b99-6074ac3bd0f7.png)

**Comment by bjornreppen** [comment]
Teksten henger nå også for lavt.. alle 3 elementer trenger å lines opp vertikalt

![image](https://user-images.githubusercontent.com/281359/66498059-bf41f480-eabd-11e9-8e75-5b6a710dd483.png)

**Comment by helemork** [comment]
Utdatert.
