### ISSUE TITLE
Datakilde: Trangt mellom ikon og tekst

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart#1579]
![image](https://user-images.githubusercontent.com/281359/66324334-80793680-e925-11e9-83e4-5feab12d693e.png)

**Comment by helemork** [comment]
Hvor er vi nå?
Er dette knappene under Datakilder nederst?

Isåfall trenger de mer fiks enn bare det :D

**Comment by bjornreppen** [comment]
Ja, den knappen under der

ons. 9. okt. 2019, 09:54 skrev helemork <notifications@github.com>:

**Comment by helemork** [comment]
Utdatert
