### ISSUE TITLE
Naturvernområder har litt merkelig måte å vise ting på 

### ISSUE THREAD

**Issue by svetlnaumova** [Artsdatabanken/nin-kart#1586]
Er det en grunn til at naturreservat og nasjonalpark vises to ganger? 
![Naturreservat](https://user-images.githubusercontent.com/43623201/66464642-a87cad00-ea7f-11e9-82e0-325684ebadca.jpg)

**Comment by helemork** [comment]
@bjørn?

**Comment by bjornreppen** [comment]
Har jeg tukla med det.. ja... er det bra nå?

**Comment by svetlnaumova** [comment]
Ble litt bedre, men nå mangler det en del...
![Naturvernområde](https://user-images.githubusercontent.com/43623201/66471341-73765780-ea8b-11e9-92d3-1d94d8f2014f.jpg)

**Comment by bjornreppen** [comment]
Har organisert hierarkiet likedan som Miljødirektoratet har gjort her: https://www.miljodirektoratet.no/ansvarsomrader/vernet-natur/norges-verneomrader/

Flere av kateogoriene finnes derfor under Annet vern - VV-VF-AV

**Comment by svetlnaumova** [comment]
Noen av logoene mangler i navigasjonsmenyen :(

**Comment by svetlnaumova** [comment]
Også, hvis man navigerer til et nivå under (f.eks. "Annet vern") og så kommer tilbake til "Naturvernområde" ved hjelp av navigasjonsmenyen, så vises det igjen som før, men 2 stk naturreservat og 2 nasjonalparker.

**Comment by bjornreppen** [comment]
Logoer er nå på plass.  Jeg får ikke til å reprodusere den siste.  Kan det være at en gammel metadata.json ligger i cachen din?

**Comment by svetlnaumova** [comment]
Ja, sannsynligvis var det cache. Fungerer nå :)

**Comment by bjornreppen** [comment]
Ser det fortsatt er et issue med "Fastlands-Norge"

**Comment by bjornreppen** [comment]
Fixed in https://github.com/Artsdatabanken/naturvern-lastejobb/commit/35cb7fff45f43d404ba2efdc56db21aa73b5a96d
