### ISSUE TITLE
Skjedde noe rart med kommunevåpen til Tønsberg?

### ISSUE THREAD

**Issue by svetlnaumova** [Artsdatabanken/nin-kart#1587]
![Tønsberg](https://user-images.githubusercontent.com/43623201/66466146-7e78ba00-ea82-11e9-9bab-9d7cbc440ff8.jpg)

**Comment by bjornreppen** [comment]
Vi har brukt https://imagemagick.org så den har nok av en eller annen grunn skippa ut ved konvertering før den hadde tegna alt... og så lagra et halvferdig bilde.

**Comment by helemork** [comment]
vil påstå det er fler enn tønsberg som mangler noe her...
larvik..
holmestrand...

**Comment by bjornreppen** [comment]
Rekjørt på nye versjoner i https://github.com/Artsdatabanken/bilde-lastejobb/commit/d81a24685b64c0ebdc5dae3d85e086fd48abe51e -

![image](https://user-images.githubusercontent.com/281359/66734402-3e8b4b80-ee63-11e9-9fe7-e4ee6b8ee50a.png)


Ser ok ut nå.  Litt vanskelig å se på grunn av bug med lasting av bildene (dukker opp og forsvinner ved musbevegelser)
