### ISSUE TITLE
Lokalitet og Url

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart#1590]
Blokkerer #1575
- [x] Quickfix for å ta oss til riktig sted er laget. Men mindre tungt oppslag...
- [ ] når man søker, ta oss til riktig lenke @bjornreppen 

Drøm i fremtiden:
- [ ] når man bytter mellom begge veier der <-- her må vi tenke litt lurt! nå forblir man på sopp hvis man bytter fane, men går til lokalitetsiden hvis man trykker på knappen i markøren som tydelig tar deg vekk.

**Comment by bjornreppen** [comment]
Hva legger vi i å ta oss til riktig lenke?  Fungerer det nå?

**Comment by helemork** [comment]
Ja, det fungerer fordi jeg overskriver det som skjer om jeg husker rett. Husker ikke helt hva jeg gjorde men det er tungvindt. Ikke en hastesak.

**Comment by helemork** [comment]
Ikke lenger relevant for NiN-kart 2.0
