### ISSUE TITLE
Arter: Ikoner

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart#1597]
https://git.artsdatabanken.no/Repository/9b8fbb4c-b3d7-4ebc-8fef-0d2438628c55/master/Tree/Content/species

- Ikke vitenskapelige navn på filene
- Mangler lisenser

Foreslår at man sjekker ut om disse kan deles med http://phylopic.org  .. .da vil de automatisk bli lastet inn.

**Comment by helemork** [comment]
- [ ] Lage ikon for art (øvre nivå)
- [ ] Passe på at bilder som brukes på våre steder alltid er bilder på noe som finnes som underelement (typ: pattedyr kan ikke ha bilde av en kenguru, for vi har ikke kenguru) - sånn sett kvitte oss med eksotiske arter

### Coverbilder
- [ ] Mulighet for å på noen av dem velge dette som ønsket ikon. (Hvordan?)
- [ ] Arter som f.eks villsvin burde ikke være hoveddyr for pattedyr. Henger sammen med punkt over. Vi burde hatt noe erkenorsk. F.eks en eller annen tag i metadata på dyret om hvor vanlig den er? Og så velge det vanligste? idk
- [ ] Helst unngå at fremmedarter velges som coverbilder

**Comment by helemork** [comment]
Midlertidig i påvente av egenskapsbank - lag en prioriteringsoverkjøringsjson, som hvem som helst kan redigere i for å sette arter man vil ha som omslagsarter! 
typ:

prioritertomslag[ulv, grevling, fossekall, spurv]

I dyregruppene disse forekommer i, velges dette dyret som omslag.
hvor konflikter løses med at første element har høyest prioriet.

**Comment by helemork** [comment]
Ikke lenger relevant
