### ISSUE TITLE
Manglende kartlag i kartet

### ISSUE THREAD

**Issue by svetlnaumova** [Artsdatabanken/nin-kart#1610]
Det mangler en del kartlag, sannsynligvis er det flere enn de som jeg fant:

- [x] dypt nedskåret dallandskap med hei under skoggrensen med bebygde områder

- [x] dypt nedskåret dallandskap under skoggrensen med innsjø og bebygde områder

- [x]  dypt nedskåret dallandskap under skoggrensen med innsjø

- [x] dypt nedskåret dallandskap med bart fjell over skoggrensen med innsjø

- [x] dypt nedskåret dallandskap under skoggrensen med større innsjø

- [x] dypt nedskåret dallandskap under skoggrensen med større innsjø og bebygde områder

- [x] dypt nedskåret dallandskap med hei under skoggrensen med større innsjø

- [x] dypt nedskåret dallandskap med bart fjell over skoggrensen med større innsjø

- [x] åpent dallandskap med bart fjell over skoggrensen

- [x] åpent dallandskap med bart fjell over skoggrensen dominert av isbre

- [x] åpent dallandskap under skoggrensen med innsjø

- [x] åpent dallandskap under skoggrensen med innsjø med jordbruksdominans

- [x] åpent dallandskap under skoggrensen med innsjø og bebygde områder

- [x] åpent dallandskap under skoggrensen med innsjø med bebygde områder og jordbruksdominans 

- [x] åpent dallandskap under skoggrensen med innsjø og tett bebyggelse

- [x] åpent dallandskap med hei under skoggrensen med innsjø

- [x] åpent dallandskap med hei under skoggrensen med innsjø og bebygde områder

- [x] åpent dallandskap med hei over skoggrensen med innsjø

- [x] åpent dallandskap med bart fjell over skoggrensen med innsjø

- [x] åpent dallandskap under skoggrensen med større innsjø

- [x] åpent dallandskap under skoggrensen med større innsjø og bebygde områder

- [x] åpent dallandskap under skoggrensen med større innsjø med bebygde områder og jordbruksdominans 

- [x] åpent dallandskap under skoggrensen med større innsjø og tett bebyggelse

- [x] åpent dallandskap under skoggrensen med større innsjø med tett bebyggelse og jordbruksdominans 

- [x] åpent dallandskap under skoggrensen med større innsjø og by

- [x] åpent dallandskap med hei under skoggrensen med større innsjø

- [x] åpent dallandskap med hei under skoggrensen med større innsjø og bebygde områder

- [x] åpent dallandskap med hei under skoggrensen med større innsjø og tett bebyggelse

- [x] åpent dallandskap med hei over skoggrensen og større innsjø

- [x] åpent dallandskap med bart fjell over skoggrensen med større innsjø

- [x] relativt åpent dallandskap under skoggrensen 

- [x] relativt åpent dallandskap under skoggrensen med jordbruksdominans

- [x] relativt åpent dallandskap under skoggrensen med bebygde områder 

- [x] relativt åpent dallandskap under skoggrensen med bebygde områder og jordbruksdominans

- [x] relativt åpent dallandskap under skoggrensen med tett bebyggelse

- [x] relativt åpent dallandskap under skoggrensen med tett bebyggelse og jordbruksdominans

- [x] relativt åpent dallandskap med hei under skoggrensen 

- [x] relativt åpent dallandskap med hei under skoggrensen med bebygde områder 

- [x] relativt åpent dallandskap med hei under skoggrensen med tett bebyggelse

- [x] relativt åpent dallandskap med hei over skoggrensen 

- [x] relativt åpent dallandskap med hei over skoggrensen med bebygde områder 

- [x] relativt åpent dallandskap med bart fjell over skoggrensen 

- [x] relativt åpent dallandskap med bart fjell over skoggrensen dominert av isbre

- [x] relativt åpent dallandskap under skoggrensen med innsjø

- [x] relativt åpent dallandskap under skoggrensen med innsjø og bebygde områder 

- [x] relativt åpent dallandskap under skoggrensen med innsjø med bebygde områder og jordbruksdominans

- [x] relativt åpent dallandskap under skoggrensen med innsjø og tett bebyggelse

- [x] relativt åpent dallandskap med hei under skoggrensen med innsjø 

- [x] relativt åpent dallandskap med hei under skoggrensen med innsjø og bebygde områder 

---
- [ ] Naturtyper alle nivå
- [x] KLG alle barn av hovedtrinn

**Comment by svetlnaumova** [comment]
Fant flere!

- relativt åpent dallandskap med hei over skoggrensen med innsjø

- relativt åpent dallandskap med bart fjell over skoggrensen med innsjø dominert av isbre

- relativt åpent dallandskap under skoggrensen med større innsjø

- relativt åpent dallandskap under skoggrensen med større innsjø og bebygde områder

- relativt åpent dallandskap under skoggrensen med større innsjø med bebygde områder og jordbruksdominans

- relativt åpent dallandskap under skoggrensen med større innsjø og tett bebyggelse

- relativt åpent dallandskap med hei under skoggrensen med større innsjø

- relativt åpent dallandskap med hei under skoggrensen med større innsjø og bebygde områder 

- relativt åpent dallandskap med hei over skoggrensen med større innsjø

- relativt åpent dallandskap med hei over skoggrensen med større innsjø og bebygde områder 

- relativt åpent dallandskap med bart fjell over skoggrensen med større innsjø 

- relativt åpent dallandskap med bart fjell over skoggrensen med større innsjø dominert av isbre 

- nedskåret dallandskap under skoggrensen

- nedskåret dallandskap under skoggrensen med jordbruksdominans

- nedskåret dallandskap under skoggrensen med bebygde områder 

- nedskåret dallandskap under skoggrensen med bebygde områder og jordbruksdominans

- nedskåret dallandskap under skoggrensen med tett bebyggelse 

- nedskåret dallandskap med hei under skoggrensen

- nedskåret dallandskap med hei under skoggrensen med bebygde områder 

- nedskåret dallandskap med hei over skoggrensen

- nedskåret dallandskap med bart fjell over skoggrensen

- nedskåret dallandskap med bart fjell over skoggrensen med bebygde områder 

- nedskåret dallandskap med bart fjell over skoggrensen dominert av isbre 

- nedskåret dallandskap under skoggrensen med innsjø

- nedskåret dallandskap under skoggrensen med innsjø og bebygde områder 

- nedskåret dallandskap under skoggrensen med innsjø og tett bebyggelse 

- nedskåret dallandskap med hei under skoggrensen med innsjø

- nedskåret dallandskap med hei under skoggrensen med innsjø og bebygde områder 

- nedskåret dallandskap med hei over skoggrensen med innsjø

- nedskåret dallandskap med bart fjell over skoggrensen med innsjø

- nedskåret dallandskap med bart fjell over skoggrensen med innsjø dominert av isbre

- nedskåret dallandskap under skoggrensen med større innsjø

- nedskåret dallandskap under skoggrensen med større innsjø og bebygde områder 

- nedskåret dallandskap under skoggrensen med større innsjø med bebygde områder og jordbruksdominans

- nedskåret dallandskap med hei under skoggrensen med større innsjø

- nedskåret dallandskap med hei over skoggrensen med større innsjø

- nedskåret dallandskap med bart fjell over skoggrensen med større innsjø

- dypt nedskåret dallandskap under skoggrensen

- dypt nedskåret dallandskap under skoggrensen med bebygde områder 

- dypt nedskåret dallandskap under skoggrensen med tett bebyggelse 

- dypt nedskåret dallandskap med hei under skoggrensen

- dypt nedskåret dallandskap med hei under skoggrensen med bebygde områder 

- dypt nedskåret dallandskap med hei over skoggrensen

- dypt nedskåret dallandskap med bart fjell over skoggrensen

- dypt nedskåret dallandskap med bart fjell over skoggrensen dominert av isbre

- dypt nedskåret dallandskap under skoggrensen med innsjø

- dypt nedskåret dallandskap under skoggrensen med innsjø og bebygde områder

**Comment by svetlnaumova** [comment]
Og enda litt flere. Tror det er alt denne gangen. 

- kystnært innlandsslettelandskap med bart fjell over skoggrensen med høyt våtmarkspreg

- kystnært innlandsslettelandskap med hei over skoggrensen med høyt våtmarkspreg

- kystnært innlandsslettelandskap med hei under skoggrensen med høyt våtmarkspreg

- kystnært innlandsslettelandskap under skoggrensen med høyt våtmarkspreg, bebygde områder og jordbruksdominans

- kystnært innlandsslettelandskap under skoggrensen med høyt våtmarkspreg og bebygde områder

- kystnært innlandsslettelandskap under skoggrensen med høyt våtmarkspreg og jordbruksdominans

- kystnært innlandsslettelandskap under skoggrensen med høyt våtmarkspreg

- kystnært innlandsslettelandskap med bart fjell over skoggrensen dominert av isbre

- kystnært innlandsslettelandskap med bart fjell over skoggrensen

- kystnært innlandsslettelandskap med hei over skoggrensen

- kystnært innlandsslettelandskap med hei under skoggrensen

- kystnært innlandsslettelandskap under skoggrensen med by

- kystnært innlandsslettelandskap under skoggrensen med tett bebyggelse og jordbruksdominans

- kystnært innlandsslettelandskap under skoggrensen med tett bebyggelse

- kystnært innlandsslettelandskap under skoggrensen med bebygde områder og jordbruksdominans

- kystnært innlandsslettelandskap under skoggrensen med bebygde områder

- kystnært innlandsslettelandskap under skoggrensen

- innlandsslettelandskap med bart fjell over skoggrensen med høyt våtmarkspreg

- innlandsslettelandskap med hei over skoggrensen med høyt våtmarkspreg

- innlandsslettelandskap med hei under skoggrensen med høyt våtmarkspreg

- innlandsslettelandskap under skoggrensen med høyt våtmarkspreg og tett bebyggelse

- innlandsslettelandskap under skoggrensen med høyt våtmarkspreg, bebygde områder og jordbruksdominans

- innlandsslettelandskap under skoggrensen med høyt våtmarkspreg og bebygde områder

- innlandsslettelandskap under skoggrensen med høyt våtmarkspreg

- innlandsslettelandskap med bart fjell over skoggrensen dominert av isbre

- innlandsslettelandskap med bart fjell over skoggrensen

- innlandsslettelandskap med hei over skoggrensen

- grunne daler i ås- og fjellandskap med hei under skoggrensen med bebygde områder

- grunne daler i ås- og fjellandskap med hei over skoggrensen

- grunne daler i ås- og fjellandskap med bart fjell over skoggrensen

- grunne daler i ås- og fjellandskap dominert av isbre med bart fjell over skoggrensen

- slakt til småkupert ås- og fjellandskap under skoggrensen

- slakt til småkupert ås- og fjellandskap under skoggrensen med jordbruksdominans

- slakt til småkupert ås- og fjellandskap under skoggrensen med bebygde områder

- slakt til småkupert ås- og fjellandskap under skoggrensen med bebygde områder og jordbruksdominans

- slakt til småkupert ås- og fjellandskap under skoggrensen med tett bebyggelse

- slakt til småkupert ås- og fjellandskap under skoggrensen med tett bebyggelse og jordbruksdominans

- slakt til småkupert ås- og fjellandskap under skoggrensen med by 

- slakt til småkupert ås- og fjellandskap med hei under skoggrensen

- slakt til småkupert ås- og fjellandskap med hei under skoggrensen med bebygde områder 

- slakt til småkupert ås- og fjellandskap med hei over skoggrensen

-  slakt til småkupert ås- og fjellandskap med hei over skoggrensen med bebygde områder 

- slakt til småkupert ås- og fjellandskap med bart fjell over skoggrensen

- slakt til småkupert ås- og fjellandskap dominert av isbre med bart fjell over skoggrensen

- middels kupert ås- og fjellandskap under skoggrensen

- middels kupert ås- og fjellandskap under skoggrensen med jordbruksdominans

- middels kupert ås- og fjellandskap under skoggrensen med bebygde områder

- middels kupert ås- og fjellandskap under skoggrensen med bebygde områder og jordbruksdominans

- middels kupert ås- og fjellandskap under skoggrensen med tett bebyggelse 

- middels kupert ås- og fjellandskap under skoggrensen med tett bebyggelse og jordbruksdominans

- middels kupert ås- og fjellandskap med hei under skoggrensen

- middels kupert ås- og fjellandskap med hei under skoggrensen med jordbruksdominans

- middels kupert ås- og fjellandskap med hei under skoggrensen med bebygde områder

- middels kupert ås- og fjellandskap med hei over skoggrensen

- middels kupert ås- og fjellandskap med hei over skoggrensen med bebygde områder

- middels kupert ås- og fjellandskap med bart fjell over skoggrensen

- middels kupert ås- og fjellandskap dominert av isbre med bart fjell over skoggrensen

- kupert ås- og fjellandskap under skoggrensen

- kupert ås- og fjellandskap under skoggrensen med bebygde områder

- kupert ås- og fjellandskap under skoggrensen med bebygde områder og jordbruksdominans

- kupert ås- og fjellandskap under skoggrensen med tett bebyggelse

- kupert ås- og fjellandskap med hei under skoggrensen 

- kupert ås- og fjellandskap med hei over skoggrensen 

- kupert ås- og fjellandskap med bart fjell over skoggrensen 

- kupert ås- og fjellandskap dominert av isbre med bart fjell over skoggrensen 

- tindepreget ås- og fjellandskap under skoggrensen 

- tindepreget ås- og fjellandskap under skoggrensen med bebygde områder 

- tindepreget ås- og fjellandskap under skoggrensen med tett bebyggelse

- tindepreget ås- og fjellandskap med hei under skoggrensen

- tindepreget ås- og fjellandskap med hei over skoggrensen

- tindepreget ås- og fjellandskap med bart fjell over skoggrensen

- tindepreget ås- og fjellandskap dominert av isbre med bart fjell over skoggrensen

**Comment by helemork** [comment]
gradienter vi mangler:

- Terrenghelning
- Terrengposisjon
- Terrenguro

**Comment by helemork** [comment]
- arter 
- gradient: alle lkg
- alt fra milj.dir. som ennå venter på godkjenning

**Comment by bjornreppen** [comment]
Denne gjør også at de blir vanskelig å finne: https://github.com/Artsdatabanken/nin-kart/issues/1525

**Comment by bjornreppen** [comment]
KLG: https://github.com/Artsdatabanken/nin-data-lastejobb/commit/e505457ec169778fab983ee0dac9d2fdf61f6740

**Comment by bjornreppen** [comment]
This turned out to be a rather epic size issue......

**Comment by svetlnaumova** [comment]
@helemork påpekte at det faktisk kan hende at mange av disse kartlagene er tilstede, men noen områder er såpass små at det ikke er enkelt å se dem, selv når man zoomer inn og setter på høy fargekontrast.

**Comment by bjornreppen** [comment]
Ja, vi må prøve å finne på noe for de også slik at de blir synlige.
