### ISSUE TITLE
Hierarki: Layout issues

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart#1612]
![image](https://user-images.githubusercontent.com/281359/67897810-6e269d00-fb5f-11e9-8c8b-e606f4c552b5.png)

- [ ] Ting står ikke på linje
- [ ] For trangt mellom ikoner og tekst

**Comment by svetlnaumova** [comment]
Grunnen til at elementene ikke stod på linje var at ikoner hadde ulik bredde. Tror jeg har fikset det, må bare teste litt for å se om det ikke er noe som ser litt rart ut nå

![image](https://user-images.githubusercontent.com/43623201/68683557-4542d680-0567-11ea-85c7-4057ad967b31.png)
