### ISSUE TITLE
Logoer med hvit farge har blitt usynlige

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart#1614]
Eksempel Indre fosen.
![image](https://user-images.githubusercontent.com/281359/67944881-dc11a980-fbdd-11e9-90c1-6fac8afac0d9.png)

**Comment by helemork** [comment]
Hvordan skal vi løse denne? Det vil se rart ut om vi legger på skygge på samtlige element for å unngå at det inntreffer i de få som inneholder hvitfarge? @bjornreppen

**Comment by helemork** [comment]
Ser ikke på denne som et problem.
