### ISSUE TITLE
Feil i punkt-api?

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart#1623]
Bioklimatisk sone/seksjon viser feil sone/seksjon på "stedets informasjonsside". 
Eks: https://nin.artsdatabanken.no/Administrativ_grense/Territorialomr%C3%A5de/Fastlands-Norge/Sogn_og_Fjordane/Selje/lokalitet?lng=5.125777841669716&lat=62.19507682985388?informasjon

Skal være sterkt osenanisk og sørboreal (jf kartet), men stedets infomasjosside viser Svaklt kontinental og Lavalpin.

![image](https://user-images.githubusercontent.com/31729342/68288103-18cd1d00-0084-11ea-81cf-9d01603a5a07.png)
![image](https://user-images.githubusercontent.com/31729342/68288169-339f9180-0084-11ea-9b2c-6f20a2bcd9b7.png)
![image](https://user-images.githubusercontent.com/31729342/68288205-4619cb00-0084-11ea-9be8-6e1f081ebc55.png)

**Comment by bjornreppen** [comment]
På et eller annet vis hadde PCA1, PCA2 blitt mappet motsatt til SO og SE igjen.. Fixed.
