### ISSUE TITLE
Kart: Pop-up dukker opp utenfor skjermen 

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart#1624]
Ved klikk i nedre eller høyre del av skjermen forsvinner hele eller deler av popup utenfor skjermen.

![image](https://user-images.githubusercontent.com/281359/69044549-638c5480-09f5-11ea-8638-6235b9c3de84.png)

**Comment by helemork** [comment]
men om du flytter kartet, ser du den jo. Er dette egentlig et problem?
Å detektere kant på vindu er ganske mye styr i forhold til at dette er meget lett å fikse for brukeren ved å flytte på kartet. Om det du skal se på er i nedre hjørne, ser du det jo ikke spesielt godt uansett.. ?

**Comment by helemork** [comment]
Ikke lenger relevant. Popup er død-
