### ISSUE TITLE
Punkt: Visning for steder utenfor allfarvei

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart#1625]
Går man til informasjonsside for et punkt utenom allfarvei som ikke treffer et stedsnavn får man en blank side og et søkefelt utfylt med en kryptisk streng:
![image](https://user-images.githubusercontent.com/281359/69049139-7c9a0300-09ff-11ea-8374-ae6a3d4b21c6.png)

Eksempel: https://nin.artsdatabanken.no/Natur_i_Norge/lokalitet?lng=8.72995190204502&lat=64.80879734981048?informasjon

Kan man heller bare fortsette som vanlig, men ikke vise stedsnavnet?

**Comment by helemork** [comment]
Løst i NiN-kart 2.0
