### ISSUE TITLE
GetFeatureInfo - Prioritert rekkefølge

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart#1644]
- [x] NiN Landskap #1639 
- [x] Arealressurskart - AR50 - Arealtyper #1635
- [x] Naturtyper - NiN #1634 
- [x] Nasjonale laksefjorder #1633 
- [x] Løsmasser #1632

**Comment by bjornreppen** [comment]
NiN = trøbbel med CORS.  Sette opp proxy eller fokusere på andre ting?

**Comment by bjornreppen** [comment]
.. det er også mulig å starte f.eks. Chrome med CORS avslått for demoformål.. hvis man vil.

https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by bjornreppen** [comment]
Hvor fortsette nå?  .. Er det f.eks. noe behov for "teiger" eller fortsette nedover listene?
https://ws.geonorge.no/norgeskart/v1/teiger/bbox/63.39259087194857,11.069720080040636,63.39259087194857,11.069720080040636

**Comment by bjornreppen** [comment]
Denne er vel i "boks"?
