### ISSUE TITLE
Bakgrunnkartvelger "googelmapsstyle"

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart#1645]
![image](https://user-images.githubusercontent.com/31729342/70524315-312dcd00-1b45-11ea-91fb-9fe977f3c01c.png)

**Comment by runningbones** [comment]
Liker feature i test, men tror det blir enda medre om "thumbnail" viser alternativet som ikke er aktivt, Eks. Gåråtone er aktivt, thubnail viser satelitt (og motsatt)

**Comment by bjornreppen** [comment]
Fixed.
