### ISSUE TITLE
Getfeatureinfo Mdir - problemer også med browser uten CORS

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart#1647]
**Describe the bug**
Får ikke visning av Getfeatureinfo fra Naturtyper_nin_alle ved klikk i kart (på lokalitet med slike data) i brwser uten CORS-problematikk (disable-web-security --disable-gpu --user-data-dir)

Ser informasjonen i F12/network/response

#1644 

**To Reproduce**
1. Go to 'https://forvaltningsportal.test.artsdatabanken.no/?lng=9.676521245246727&lat=62.83068996597348'
2. Click on 'punkt.'
3. Click F12

**Expected behavior**
Getfeatureinfo fra Naturtyper_nin_alle dukket opp i fanen "punkt"

**Screenshots**
![image](https://user-images.githubusercontent.com/31729342/70606222-529dc000-1bfc-11ea-8a44-99aa1402d489.png)

**Desktop (please complete the following information):**
 - Browser [Chrome, "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-web-security --disable-gpu --user-data-dir=~/chromeTemp

**Additional context**

**Comment by bjornreppen** [comment]
Finnes faktaark?

**Comment by bjornreppen** [comment]
Kom gjerne med tilbakemelding på hvilke felt som skal vises i de forskjellige boksene..

**Comment by bjornreppen** [comment]
Fikset.  Årsak var at boksen ikke ble fullført siden dataene ikke hadde lyst til å komme ned..

**Comment by runningbones** [comment]
Faktaark for Naturtyper_nin_alle  ligger her: (eksempel URL) https://nin-faktaark.miljodirektoratet.no/naturtyper/?id=NINFP1810030453

ID for det enkelte objekt finnes i getfeatureinfo, attributtnavn: "NiNID="

**Comment by bjornreppen** [comment]
Får redirect 307 i iframe, ikke tid til å forske på nå.. faktaark kommer i eget vindu.
