### ISSUE TITLE
6SO - bioklimatisk sone: feil i fargebruk

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart#1658]
**Describe the bug**
Fargebruk i tegning av 6SO - bioklimatisk sone er helt feil. 

**To Reproduce**

1. Go to https://nin.artsdatabanken.no/Natur_i_Norge/Natursystem/Beskrivelsessystem/Regional_naturvariasjon/Bioklimatisk_sone?lng=8.479816911761189&lat=61.55368389997229?kartlag'
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/31729342/73650273-0dd55900-4682-11ea-9f7b-1eb665bb5e87.png)

**Comment by bjornreppen** [comment]
De "ubrukte" trinnene 5 og 6 ble automatisk tilordnet overlappende verdier.

Fixed in https://github.com/Artsdatabanken/nin-data-lastejobb/commit/6cb3842e71e2165f196c231a42159a41f0397132
