### ISSUE TITLE
LA - endret URL til artsdatabanken.no

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart#1661]
**Describe the bug**
www.Artsdatabanken.no har nå endret URL til NiN-typesider. URL inneholder nå "TI" (som i NiN-kart). Eksisterende  lenker i NiN-kart til www.Artsdatabanken.no må oppdateres til ny struktur.

Eks. 
Før: https://artsdatabanken.no/nin/LA/K/F/26
Nå: https://artsdatabanken.no/nin/LA/TI/K/F/26

**Comment by bjornreppen** [comment]
Kommer denne URLen kanskje snart ut av egenskapsbanken?

**Comment by bjornreppen** [comment]
Og endringen som ga nye data: https://github.com/Artsdatabanken/landskap-lastejobb/commit/1b671c3eb2e8f61794ceb0ddcc503abe3d6a9ea9
