### ISSUE TITLE
Administrative områder: kun visning av fastlandsnorge i kart

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart#1664]
**Describe the bug**
Administrative områder: kun visning av fastlandsnorge i kart

**To Reproduce**
1. Go to 'https://nin.artsdatabanken.no/Administrativ_grense/Territorialomr%C3%A5de?kartlag' eller https://nin.artsdatabanken.no/Administrativ_grense/Kontinentalsokkel?kartlag
2. See error

**Comment by helemork** [comment]
Nope, ser bra ut
