### ISSUE TITLE
Søk 

### ISSUE THREAD

**Issue by danam2** [Artsdatabanken/nin-kart#1672]
Prøver å søke f.eks. koden L3, returnerer feil/riktig resultatsett (randomly)

**Comment by bjornreppen** [comment]
Denne lukter litt som at bare 1 av nodene fungerer riktig . Hva tror du @Myrdrahl ?

**Comment by bjornreppen** [comment]
Feil i klientkoden, viser ikke siste resultat når knappetrykkene kommer hyppig.
