### ISSUE TITLE
Klikk i kart gir feilmelding

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart#1678]
**Describe the bug**
Klikk i kart gir kun en tom side med "repot feedback"

**To Reproduce**
1. Go to 'https://nin.artsdatabanken.no/Natur_i_Norge/Landskap/Landskapsgradient/Arealbruksintensitet?kartlag'
2. Click on 'et sted i norge.'
3. See error

**Comment by bjornreppen** [comment]
Denne var rettet i https://github.com/Artsdatabanken/nin-kart/commit/1930774e339dc28e9253769ddf6664f8552be682 - men den nye versjonen lå bare på test.
