### ISSUE TITLE
Info om punkt er rart

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart#1679]
Gå til info om dette punktet gir merkelig søkeboks

![image](https://user-images.githubusercontent.com/281359/75916019-d65ff500-5e57-11ea-881c-8ac80d5d8b3d.png)

![image](https://user-images.githubusercontent.com/281359/75915979-c9430600-5e57-11ea-8ecb-098a7c6d7591.png)

**Comment by helemork** [comment]
utdatert
