### ISSUE TITLE
Klikk på Se mer.. gir bare Se mindre..

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart#1681]
Gå til http://localhost:3003/Administrativ_grense/Territorialomr%C3%A5de/Fastlands-Norge/Innlandet/Dovre/lokalitet?lng=9.349254429149006&lat=62.0386799588193?informasjon

Klikk på Se mer...-teksten, mer endres til mindre.. ingenting annet dukker opp.

![image](https://user-images.githubusercontent.com/281359/75948904-f79b0280-5ea4-11ea-92a9-900717592bea.png)

**Comment by helemork** [comment]
Ikke relevant i 2.0 (samt. duplikat issue)
