### ISSUE TITLE
Feil cursor på se mer

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart#1682]
Gå til http://localhost:3003/Administrativ_grense/Territorialomr%C3%A5de/Fastlands-Norge/Innlandet/Dovre/lokalitet?lng=9.349254429149006&lat=62.0386799588193?informasjon

Plasser mouse cursor over "Se mer...".  Cursor skulle endret seg og indikert at teksten er klikkbar.  Det skjer ikke.

**Comment by helemork** [comment]
Ikke relevant lengre
