### ISSUE TITLE
Tilbakemeldinger og ønsker: NA i nin-kart

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart#1700]
1. overskrift/tittel:  Arild ønsker at det skal stå NiN-kart (ikke bare Natur i Norge)
2. Hamburgermeny, gjenskap det meste av den som ligger i prod. Ikke sikkert vi trenger direktelenke til alle rotpunkter i katalog med ny logikk. 
![image](https://user-images.githubusercontent.com/31729342/94657680-16aa2780-0302-11eb-9d29-1bb1ee8173cd.png)
3. Info-side er nå helt borte. Bør vel ha en eller annen visning av hvilke LKM-er NA er bygd opp av, areal kartlagt+++. Også LA mangler info nå. 
4. ikke lenger mulig å "kombinere" kart, funksjon for "husk" er tatt bort. Vurder om vi kan gjeninnføre (husk og "mine kartlag")

**Comment by bjornreppen** [comment]
Fixed.
