### ISSUE TITLE
Display info about multiple 'NAT'-objects

### ISSUE THREAD

**Issue by olsoybakk** [Artsdatabanken/nin-kart#1716]
Løsningen viser ikke info om mer enn en kartlegging. Det blir litt misvisende når det finnes flere.

**Comment by olsoybakk** [comment]
@runningbones Endelig litt NiN-jobbings 🤓 

Sjekk her https://nin.test.artsdatabanken.no/Natur_i_Norge?lng=10.314044784206606&lat=63.31792650579916
I følge [faktaark](https://nin-faktaark.miljodirektoratet.no/kartleggingsenheter?id=NIN5026935), skal det være uLKM på denne. Nå blir ikke uLKM lagt inn i basen, men jeg har høsta data og kan slenge det inn.

**Comment by runningbones** [comment]
Ønsker visning av uLKM. Hvilken uLKM som registreres er knyutta til hvilken hovedtype som er kartlagt. Ønsker at uLKM eksponeres etter type, før beskrivelsesvariabler vises: 
![image](https://user-images.githubusercontent.com/31729342/132633194-70c4c80b-4469-4d1b-97f8-01ac1ea7f219.png)

**Comment by runningbones** [comment]
Klarte først nå å innse konsekvens av issue: tror vi må en måte for å vise multiple NAT-objekt i samme punkt. eks: 
![image](https://user-images.githubusercontent.com/31729342/135446961-9b9b5d9c-0bd5-465c-9917-487a7351486d.png)

Her får bruker kun informasjon om en 20% fraksjon av NAT, resterende 80% er utilgjengelig. Usikker på eksakt UX, men kan vise NAT som liste med fraksjon, expand og BS under?

**Comment by olsoybakk** [comment]
Ja, området du viser har kun 20%.

https://nin.test.artsdatabanken.no/Natur_i_Norge/Natursystem/Typeinndeling/Fastmarkssystemer/Fastmarksskogsmark/Lite_t%C3%B8rkeutsatte_l%C3%A5gurt-_og_b%C3%A6rlyng-_l%C3%A5gurtskoger?lng=9.205107014943259&lat=60.98255315257028
Her fant jeg et område med 20% Lågurtskog. Når jeg går inn på Natursystem, ser jeg at det også er 100% Høgstaudeskog.
Skulle vi vist begge i dette tilfellet? Det er vel også en bug som gjør at vi mister alle variablene når det er 2 _hit_ på naturtype.

**Comment by olsoybakk** [comment]
#done
